-- Natalka job pipeline. D1 (SQLite): no enums, no uuid type — ids are uuid strings generated by
-- the worker, enum-like columns are TEXT with a CHECK, timestamps are ISO-8601 UTC strings so
-- they compare and sort as text.
--
-- Retention: birth data and documents are deleted 30 days after the order; the order row itself
-- is kept forever for accounting.

CREATE TABLE orders (
  id               TEXT PRIMARY KEY,
  email            TEXT NOT NULL,
  product          TEXT NOT NULL CHECK (product IN ('natal','forecast','synastry','child','bundle')),
  locale           TEXT NOT NULL,
  country          TEXT,
  amount_minor     INTEGER NOT NULL,
  currency         TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','paid','refunded','test')),
  stripe_session_id       TEXT,
  stripe_payment_intent   TEXT,
  created_at       TEXT NOT NULL,
  paid_at          TEXT
);
CREATE INDEX orders_created ON orders (created_at);
CREATE UNIQUE INDEX orders_stripe_session ON orders (stripe_session_id) WHERE stripe_session_id IS NOT NULL;

-- Birth data is encrypted (AES-GCM) before it gets here: coordinates and time zone live inside
-- the ciphertext, only what the pipeline needs in the clear stays in columns.
CREATE TABLE charts (
  id               TEXT PRIMARY KEY,
  order_id         TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  person_no        INTEGER NOT NULL DEFAULT 1 CHECK (person_no IN (1, 2)),
  birth_ciphertext BLOB NOT NULL,
  birth_nonce      BLOB NOT NULL,
  key_version      INTEGER NOT NULL DEFAULT 1,
  unknown_time     INTEGER NOT NULL DEFAULT 0,
  gender           TEXT NOT NULL DEFAULT 'neutral' CHECK (gender IN ('female','male','neutral')),
  display_name     TEXT,
  place_label      TEXT,
  expires_at       TEXT NOT NULL,
  created_at       TEXT NOT NULL
);
CREATE INDEX charts_order ON charts (order_id);
CREATE INDEX charts_expiry ON charts (expires_at);

CREATE TABLE jobs (
  id               TEXT PRIMARY KEY,
  order_id         TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  kind             TEXT NOT NULL CHECK (kind IN ('natal','forecast','synastry','child','bundle')),
  step             TEXT NOT NULL DEFAULT 'calc'
                   CHECK (step IN ('calc','texts','pdf','email','done')),
  status           TEXT NOT NULL DEFAULT 'queued'
                   CHECK (status IN ('queued','running','failed','done')),
  attempts         INTEGER NOT NULL DEFAULT 0,
  last_error       TEXT,
  -- Engine JSON and per-section text state, so a retry resumes instead of starting over.
  payload          TEXT,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);
CREATE INDEX jobs_order ON jobs (order_id);
CREATE INDEX jobs_status ON jobs (status, updated_at);

CREATE TABLE documents (
  id               TEXT PRIMARY KEY,
  order_id         TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  storage_key      TEXT NOT NULL,
  sha256           TEXT NOT NULL,
  pages            INTEGER NOT NULL,
  bytes            INTEGER NOT NULL,
  lang             TEXT NOT NULL,
  expires_at       TEXT NOT NULL,
  created_at       TEXT NOT NULL
);
CREATE INDEX documents_order ON documents (order_id);
CREATE INDEX documents_expiry ON documents (expires_at);

CREATE TABLE email_events (
  id               TEXT PRIMARY KEY,
  order_id         TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  kind             TEXT NOT NULL,
  provider_id      TEXT,
  status           TEXT NOT NULL,
  created_at       TEXT NOT NULL
);
CREATE INDEX email_events_order ON email_events (order_id);
