"""UI labels for the computed blocks (tables, cover, TOC) per document language.

Section texts come from the LLM already localised; these are the few fixed strings the renderer
itself needs. Unknown languages fall back to English.
"""

from __future__ import annotations

from typing import Final

BODIES: Final[dict[str, dict[str, str]]] = {
    "uk": {
        "sun": "Сонце",
        "moon": "Місяць",
        "mercury": "Меркурій",
        "venus": "Венера",
        "mars": "Марс",
        "jupiter": "Юпітер",
        "saturn": "Сатурн",
        "uranus": "Уран",
        "neptune": "Нептун",
        "pluto": "Плутон",
        "chiron": "Хірон",
        "north_node": "Півн. вузол",
        "south_node": "Півд. вузол",
        "lilith": "Ліліт",
        "asc": "Асцендент",
        "mc": "MC",
        "dsc": "Десцендент",
        "ic": "IC",
        "vertex": "Вертекс",
        "pars_fortunae": "Парс Фортуни",
    },
    "en": {
        "sun": "Sun",
        "moon": "Moon",
        "mercury": "Mercury",
        "venus": "Venus",
        "mars": "Mars",
        "jupiter": "Jupiter",
        "saturn": "Saturn",
        "uranus": "Uranus",
        "neptune": "Neptune",
        "pluto": "Pluto",
        "chiron": "Chiron",
        "north_node": "North Node",
        "south_node": "South Node",
        "lilith": "Lilith",
        "asc": "Ascendant",
        "mc": "MC",
        "dsc": "Descendant",
        "ic": "IC",
        "vertex": "Vertex",
        "pars_fortunae": "Pars Fortunae",
    },
    "ru": {
        "sun": "Солнце",
        "moon": "Луна",
        "mercury": "Меркурий",
        "venus": "Венера",
        "mars": "Марс",
        "jupiter": "Юпитер",
        "saturn": "Сатурн",
        "uranus": "Уран",
        "neptune": "Нептун",
        "pluto": "Плутон",
        "chiron": "Хирон",
        "north_node": "Сев. узел",
        "south_node": "Юж. узел",
        "lilith": "Лилит",
        "asc": "Асцендент",
        "mc": "MC",
        "dsc": "Десцендент",
        "ic": "IC",
        "vertex": "Вертекс",
        "pars_fortunae": "Парс Фортуны",
    },
    "pl": {
        "sun": "Słońce",
        "moon": "Księżyc",
        "mercury": "Merkury",
        "venus": "Wenus",
        "mars": "Mars",
        "jupiter": "Jowisz",
        "saturn": "Saturn",
        "uranus": "Uran",
        "neptune": "Neptun",
        "pluto": "Pluton",
        "chiron": "Chiron",
        "north_node": "Węzeł płn.",
        "south_node": "Węzeł płd.",
        "lilith": "Lilith",
        "asc": "Ascendent",
        "mc": "MC",
        "dsc": "Descendent",
        "ic": "IC",
        "vertex": "Vertex",
        "pars_fortunae": "Punkt Szczęścia",
    },
    "de": {
        "sun": "Sonne",
        "moon": "Mond",
        "mercury": "Merkur",
        "venus": "Venus",
        "mars": "Mars",
        "jupiter": "Jupiter",
        "saturn": "Saturn",
        "uranus": "Uranus",
        "neptune": "Neptun",
        "pluto": "Pluto",
        "chiron": "Chiron",
        "north_node": "Nördl. Mondknoten",
        "south_node": "Südl. Mondknoten",
        "lilith": "Lilith",
        "asc": "Aszendent",
        "mc": "MC",
        "dsc": "Deszendent",
        "ic": "IC",
        "vertex": "Vertex",
        "pars_fortunae": "Glückspunkt",
    },
}

SIGNS: Final[dict[str, tuple[str, ...]]] = {
    "uk": (
        "Овен",
        "Телець",
        "Близнюки",
        "Рак",
        "Лев",
        "Діва",
        "Терези",
        "Скорпіон",
        "Стрілець",
        "Козоріг",
        "Водолій",
        "Риби",
    ),
    "en": (
        "Aries",
        "Taurus",
        "Gemini",
        "Cancer",
        "Leo",
        "Virgo",
        "Libra",
        "Scorpio",
        "Sagittarius",
        "Capricorn",
        "Aquarius",
        "Pisces",
    ),
    "ru": (
        "Овен",
        "Телец",
        "Близнецы",
        "Рак",
        "Лев",
        "Дева",
        "Весы",
        "Скорпион",
        "Стрелец",
        "Козерог",
        "Водолей",
        "Рыбы",
    ),
    "pl": (
        "Baran",
        "Byk",
        "Bliźnięta",
        "Rak",
        "Lew",
        "Panna",
        "Waga",
        "Skorpion",
        "Strzelec",
        "Koziorożec",
        "Wodnik",
        "Ryby",
    ),
    "de": (
        "Widder",
        "Stier",
        "Zwillinge",
        "Krebs",
        "Löwe",
        "Jungfrau",
        "Waage",
        "Skorpion",
        "Schütze",
        "Steinbock",
        "Wassermann",
        "Fische",
    ),
}

UI: Final[dict[str, dict[str, str]]] = {
    "uk": {
        "contents": "Зміст",
        "positions": "Позиції планет",
        "planet": "Планета",
        "sign": "Знак",
        "degree": "Градус",
        "house": "Дім",
        "retro": "R",
        "aspects": "Сітка аспектів",
        "date": "Дата",
        "time": "Час",
        "place": "Місце",
        "unknown_time": "час невідомий",
        "footer": "Індивідуальний розбір",
        "page": "стор.",
        "of": "з",
        "system": "Система домів",
        "placidus": "Плацидус, тропічний зодіак",
        "no_houses": "без домів (час народження невідомий)",
        "legend": "R — ретроградний рух. Доми — римськими цифрами.",
        "section": "Розділ",
        "aspect_legend": "Напружені аспекти — червоним, гармонійні — синім, з'єднання — сірим.",
    },
    "en": {
        "contents": "Contents",
        "positions": "Planet positions",
        "planet": "Planet",
        "sign": "Sign",
        "degree": "Degree",
        "house": "House",
        "retro": "R",
        "aspects": "Aspect grid",
        "date": "Date",
        "time": "Time",
        "place": "Place",
        "unknown_time": "time unknown",
        "footer": "Personal reading",
        "page": "p.",
        "of": "of",
        "system": "House system",
        "placidus": "Placidus, tropical zodiac",
        "no_houses": "no houses (birth time unknown)",
        "legend": "R — retrograde motion. Houses in Roman numerals.",
        "section": "Section",
        "aspect_legend": "Tense aspects in red, harmonious in blue, conjunctions in grey.",
    },
    "ru": {
        "contents": "Содержание",
        "positions": "Позиции планет",
        "planet": "Планета",
        "sign": "Знак",
        "degree": "Градус",
        "house": "Дом",
        "retro": "R",
        "aspects": "Сетка аспектов",
        "date": "Дата",
        "time": "Время",
        "place": "Место",
        "unknown_time": "время неизвестно",
        "footer": "Индивидуальный разбор",
        "page": "стр.",
        "of": "из",
        "system": "Система домов",
        "placidus": "Плацидус, тропический зодиак",
        "no_houses": "без домов (время рождения неизвестно)",
        "legend": "R — ретроградное движение. Дома — римскими цифрами.",
        "section": "Раздел",
        "aspect_legend": "Напряжённые аспекты — красным, гармоничные — синим, соединения — серым.",
    },
    "pl": {
        "contents": "Spis treści",
        "positions": "Pozycje planet",
        "planet": "Planeta",
        "sign": "Znak",
        "degree": "Stopień",
        "house": "Dom",
        "retro": "R",
        "aspects": "Siatka aspektów",
        "date": "Data",
        "time": "Godzina",
        "place": "Miejsce",
        "unknown_time": "godzina nieznana",
        "footer": "Analiza indywidualna",
        "page": "str.",
        "of": "z",
        "system": "System domów",
        "placidus": "Placidus, zodiak tropikalny",
        "no_houses": "bez domów (godzina urodzenia nieznana)",
        "legend": "R — ruch wsteczny. Domy — cyframi rzymskimi.",
        "section": "Rozdział",
        "aspect_legend": "Aspekty napięte na czerwono, harmonijne na niebiesko, koniunkcje na szaro.",
    },
    "de": {
        "contents": "Inhalt",
        "positions": "Planetenpositionen",
        "planet": "Planet",
        "sign": "Zeichen",
        "degree": "Grad",
        "house": "Haus",
        "retro": "R",
        "aspects": "Aspektgitter",
        "date": "Datum",
        "time": "Uhrzeit",
        "place": "Ort",
        "unknown_time": "Uhrzeit unbekannt",
        "footer": "Persönliche Deutung",
        "page": "S.",
        "of": "von",
        "system": "Häusersystem",
        "placidus": "Placidus, tropischer Tierkreis",
        "no_houses": "ohne Häuser (Geburtszeit unbekannt)",
        "legend": "R — Rückläufigkeit. Häuser in römischen Ziffern.",
        "section": "Kapitel",
        "aspect_legend": "Gespannte Aspekte rot, harmonische blau, Konjunktionen grau.",
    },
}

ROMAN: Final[tuple[str, ...]] = (
    "I",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
    "VIII",
    "IX",
    "X",
    "XI",
    "XII",
)


def body_name(lang: str, body: str) -> str:
    return BODIES.get(lang, BODIES["en"]).get(body, BODIES["en"].get(body, body))


def sign_name(lang: str, sign: str) -> str:
    keys = (
        "aries",
        "taurus",
        "gemini",
        "cancer",
        "leo",
        "virgo",
        "libra",
        "scorpio",
        "sagittarius",
        "capricorn",
        "aquarius",
        "pisces",
    )
    return SIGNS.get(lang, SIGNS["en"])[keys.index(sign)]


def ui(lang: str, key: str) -> str:
    return UI.get(lang, UI["en"]).get(key, UI["en"][key])
